# 1月18日

## 条件控制

<kbd>关系运算符</kbd>：>、<、>=、<=、==、!=

返回的结果是bool型

> 注意等号是“==”，“=”是赋值

<kbd>逻辑运算符</kbd>：and、or、not

```python
if 表达式1:
	代码块
elif 表达式2:
    代码块
...
else:
    代码块
```

> 对于上面这种条件控制，如果if语句成立，那么不再执行后面跟的elif和else语句；
>
> 对于下面这种条件控制，两个if语句都会执行

```python
if 表达式1:
	代码块
if 表达式2:
	代码块
```

<kbd>pass</kbd>：占位符

```flow
st=>start: 开始
cond1=>condition: if
cond2=>condition: elif
cond...=>condition: ...
condn=>condition: else
io1=>inputoutput: 代码块1
io2=>inputoutput: 代码块2
io...=>inputoutput: 代码块...
ion=>inputoutput: 代码块n
e=>end: 结束
st->cond1
cond1(yes)->io1->e
cond1(no)->cond2
cond2(yes)->io2->e
cond2(no)->cond...
cond...(yes)->io...->e
cond...(no)->condn
condn(yes)->ion->e
```



## 循环控制

### for语句

for \<variable> in \<sequence>:
	代码块

> \<sequence>为序列或可迭代对象

range(start, stop, step)在python3中是一个可遍历的可迭代对象

> 注意写for循环的时候不要忘记range，否则就变成遍历元组了

### while语句

while 条件表达式:
	代码块

```python
# 无限循环
while True:
	pass
```

### 嵌套循环

---

<kbd>break</kbd>：跳出本层循环结构

<kbd>continue</kbd>：跳过本次循环

```python
# 跳出内循环
for i in range(5):
    for j in range(5):
        if i == j:
            break

# 跳出外循环
for i in range(5):
    for j in range(5):
        pass
    if i == j:
    	break
```



## 推导式

### 列表推导式

```python
[表达式 for item in 可迭代对象]
[表达式 for item in 可迭代对象 if 条件判断]
```

### 字典推导式

```python
{key_表达式:value_表达式 for 表达式 in 可迭代对象}
```

### 集合推导式

* 和列表的类似，[]改成{}

* 元组没有推导式

## 错误和异常捕获

[python异常处理](https://www.bilibili.com/video/BV194411r7y9/)

### 错误

1. 没法通过其他的代码进行处理的问题
2. 语法错误
3. 逻辑错误

### 异常

* 程序执行过程中，出现的未知错误

* 语法和逻辑正确

### 常见的系统异常

* 除零异常<kbd>ZeroDividionError</kbd>
* 名称异常<kbd>NameError</kbd>
* 类型异常<kbd>TypeError</kbd>
* 索引异常<kbd>IndexError</kbd>
* 键异常<kbd>KeyError</kbd>
* 值异常<kbd>ValueError</kbd>
* 属性异常<kbd>AttributeError</kbd>
* 迭代器异常<kbd>StopIteration</kbd>
* 系统异常继承数<kbd>SystemExit</kbd><kbd>KeyboardInterrupt</kbd><kbd>GeneratorExit</kbd><kbd>Exception</kbd>

### 如何解决异常？

* 预防：添加容错代码

* 解决：

  > 捕获处理异常
  >
  > > 方案1：
  > >
  > > try...except...else...finally
  > >
  > > 方案2：
  > >
  > > [7-Python错误和异常-异常的解决-with语句-语法作用_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV194411r7y9?p=7&vd_source=cc7f184216985f4e43faef43f6a25bb6)

### 如何手动抛出异常？

* raise语句

### 自定义异常

## map，lambda，filter函数的使用

### map

`map(function, iterable, ...)`：对`iterable`中每个元素应用`function`函数，并返回迭代器。

### lambda

```
lambda arg1,arg2,arg3,...:<expression>
```

### filter

`filter(function, iterable)`：用`function`函数测试`iterable`中的每一个元素，如果返回为`True`则将元素放入返回的迭代器。